= Підказки
tivasyk <tivasyk@gmail.com>
:toc:

// ============================================================================
== Micro

Веб-сайт: https://micro-editor.github.io/[micro-editor.github.io]

=== Основні функції

 Клавіші | Команда (Ctrl+E > ...)      | Опис
 ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 Alt+G   | set keymenu <true>          | Підказка з основних скорочень
 Ctrl+G  | help                        | Посібник користувача
 Ctrl+E  |                             | Командний рядок micro
         | help commands               | Посібник: команди
         | help defaultkeys            | Посібник: клавіатурні скороченняàg

=== Файли

 Клавіші | Команда (Ctrl+E > ...)      | Опис
 ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 Ctrl+O  | open <файл>                 | Відкрити файл...
 Ctrl+S  | save <файл>                 | Зберегти до файлу...
 Ctrl+Q  | quit                        | Закрити документ/вкладку (й вийти)

=== Редагування тексту

 Клавіші | Команда (Ctrl+E > ...)      | Опис
 ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 Ctrl+X  |                             | Вирізати фрагмент
 Ctrl+C  |                             | Копіювати фрагмент
 Ctrl+V  |                             | Вставити фрагмент
 Ctrl+Z  |                             | Скасувати виправлення
 Ctrl+Y  |                             | Повернути скасоване виправлення
 Ctrl+A  |                             | Виділити все

=== Пошук та заміна

 Клавіші | Команда (Ctrl+E > ...)      | Опис
 ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 Ctrl+F  |                             | Пошук...
 Ctrl+N  |                             | Знайти наступне
 Ctrl+P  |                             | Знайти попереднє
         | replace <текст> <заміна>    | Знайти «текст» і замінити

=== Області екрану

 Клавіші | Команда (Ctrl+E > ...)      | Опис
 ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
         | vsplit <файл>               | Нова область праворуч поточної
         | hsplit <файл>               | Нова область під поточною
 Ctrl+W  |                             | Перейти до наступної області
 
=== Вкладки

 Клавіші | Команда (Ctrl+E > ...)      | Опис
 ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 Ctrl+T  | tab <файл>                  | Відкрити нову вкладку
 Alt+,   |                             | Попередня вкладка
 Alt+.   |                             | Наступна вкладка
         | tabswitch <закладка>        | Перейти до закладки (ім'я/номер)

=== Макрокоманди

 Клавіші | Команда (Ctrl+E > ...)      | Опис
 ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 Ctrl+U  |                             | Початок/кінець запису макрокоманди
 Ctrl+J  |                             | Відтворити макрокоманду

=== Налаштування

 Клавіші | Команда (Ctrl+E > ...)      | Опис
 ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 Ctrl+R  | set ruler true              | Показати/сховати номери рядків
         | set autoindent true         | Автоматичний відступ
         | set autosave false          | Автозбереження файлу
         | set colorcolumn 80          | Підсвітити колонку за номером
         | set colorscheme default     | Вибір схеми розфарбовування коду
         | set cursorline true         | Підсвітити поточний рядок
         | set savecursor false        | Запам'ятовувати позицію курсора
         | set scrollbar false         | Показати/сховати індикатор прокрутки
         | set softwrap true           | «М'який» переніс рядків на екрані
         | set tabstospaces false      | Табуляція пробілами?

         
// ============================================================================
== Ranger

Веб-сайт: https://ranger.github.io/[ranger.github.io]

=== Основні функції

 Клавіші | Команда (:)                 | Опис
 ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 :       |                             | Консоль команд ranger
 $, !, s | :shell                      | Консоль команд оболонки (shell)
 Q       | :quitall                    | Вийти, закривши всі вкладки
         | :exit                       | Те саме, що quitall

=== Навігація

 Клавіші | Команда (:)                 | Опис
 ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 jk ↑↓   |                             | Вгору, вниз
 h  ←    |                             | Ліворуч (батьківська тека)
 l  →    |                             | Праворуч (підтека, відкрити файл)

=== Операції з файлами

 Клавіші | Команда (:)                 | Опис
 ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 yy      | : copy %s                   | Копіювати файл/файли (до «буфера»)
 dd      | : cut %s                    | Вирізати файл/файли (до «буфера»)
 pp      | : paste %s                  | Вставити файл/файли (з «буфера»)

 yd      |                             | Копіювати ім'я теки
 yn      |                             | Копіювати ім'я файлу
 yp      |                             | Копіювати повний шлях

 ya      |                             | Вирізати файл і додати до буфера
 da      |                             | Копіювати файл і додати до буфера
 
 <Enter> | : open ...                  | Відкрити файл (додаток за замовчуванням)
 r       | : open_with ...             | Відкрити файл за допомогою…

=== Позначки файлів

 Клавіші | Команда (:)                 | Опис
 ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 t       |                             | Позначити файл зірочкою (*)
 "!      |                             | Позначити файл довільним символом (!)

 
=== Вкладки

 Клавіші | Команда (:)                 | Опис
 ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 Ctrl+N  |                             | 
 Tab     |                             | Перейти до наступної вкладки
 Alt+<N> |                             | Перейти до вкладки за номером (1..9)
 q       | : quit                      | Закрити вкладку (і вийти, якщо остання)


// ============================================================================
== Links

...


// ============================================================================
== Bash

...


// ============================================================================
== Screen

...


// ============================================================================
== Pass / Gopass

Веб-сайт: https://www.passwordstore.org/[passwordstore.org]

=== Ініціалізація сховища

 Команда                               | Опис
 ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 pass init                             | Створити нове сховище паролів
                                       | (~/.password-store)
                                       
=== Використання

 Команда                               | Опис
 ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 pass list                             | Показати структуру/перелік паролів
                                       | у сховищі
 pass insert <шлях ключа>              | Створити ключ з новим паролем
 pass insert -m <шлях ключа>           | Створити ключ з багаторядковим записом 
                                       | (пароль має йти першим рядком)
 pass generate <шлях ключа> <довжина>  | Створити ключ і автоматично згенерувати
                                       | пароль визначеної довжини
 pass show <шлях ключа>                | Показати пароль зі сховища
 pass show -c <шлях ключа>             | Копіювати пароль до буфера обміну
 pass show -q <шлях ключа>             | Показати пароль як QRcode
 pass edit <шлях ключа>                | Редагувати збережений пароль
 pass find <текст>                     | Шукати ключі за назвою
 pass grep <опції> <текст>             | Шукати ключі з використанням grep
 pass delete [-r] <шлях ключа>         | Видалити ключ і пароль (рекурсивно)
 
// ============================================================================
== Asciidoc

Підручник: https://asciidoctor.org/docs/asciidoc-writers-guide/[asciidoctor.org/docs/asciidoc-writers-guide]


// ============================================================================
== Pacman

Підручник: https://wiki.archlinux.org/index.php/Pacman/Rosetta[wiki.archlinux.org]

=== Поновлення встановлених пакунків

 Команда                               | Опис
 ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 pacman -Syu                           | Поновити всі встановлені пакунки

=== Пошук і встановлення пакунків

 Команда                               | Опис
 ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 pacman -Ss <пакунок>                  | Шукати пакунок за іменем в сховищах
 pacman -S <пакунок>                   | Встановити пакунок за іменем
 pacman -Si <пакунок>                  | Детальна інформацію про пакунок
 pacman -Q                             | Повний перелік встановлених пакунків
 pacman -Qs <пакунок>                  | Шукати пакунок серед встановлених

=== Видалення пакунків і залежностей

 Команда                               | Опис
 ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 pacman -R $(pacman -Qdtq)             | Видалити пакунки-сироти, встановлені
                                       | як залежності
 pacman -Sc                            | Видалити з кеша старі версії пакунків

=== Налаштування

 Команда                               | Опис
 ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 ${VISUAL} /etc/pacman.conf            | Відкрити файл налаштувань редактором
 
 
// ============================================================================
== Git

Підручник: https://git-scm.com/book/uk/[git-scm.com/book] («Pro Git», переклад українською)

=== Налаштування

 Команда                               | Опис
 ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 git config --global user.name "..."   | Ім'я користувача (глобально)
 git config --global user.email "..."  | Адреса користувача (глобально)
 git config --global core.editor micro | Текстовий редактор
 git config --list                     | Перелік налаштувань
 git init                              | Початкове налаштування сховища (.git)
                                       | у робочій теці проекту 
 ${VISUAL} .gitignore                  | Перелік ігнорованих тек/файлів
                                       | (поширюється на вкладені підтеки)

=== Інформація про стан сховища

 Команда                               | Опис
 ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 git status                            | Інформація про стан локального сховища
 git status --short                    | Коротший звіт про стан локал. сховища
                                       |  ? неконтрольований файл (індекс/тека)
                                       |  ! ігнорований файл
                                       |  A новий файл
                                       |  M змінений файл
                                       |  D видалений
                                       |  R перейменований
                                       |  С копійований
 git diff                              | Звіт про зміни відносно індексованих
                                       | файлів (неіндексовані зміни)
 git diff --staged                     | Звіт про зміни відносно попереднього
 git diff --cached                     | коміту (індексовані зміни)
  
=== Відслідковування файлів

 Команда                               | Опис
 ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 git add <файл>                        | Включати теку/файл до контрольованих 
                                       | (track), індексувати зміни для коміту
 git add .                             | Включити всі теки/файли до
                                       | контрольованих та індексувати зміни
 git reset HEAD <файл>                 | Прибрати теку/файл з індексованих для
                                       | коміту
 git rm --cached <файл>                | Прибрати теку/файл з індексованих для
                                       | коміту (чим відрізняється від ―"―?),
                                       | але зберегти його на диску
 git rm <файл>                         | Видалити теку/файл з індексу та з диска
 git mv <файл> <новий шлях>            | Перейменувати/перемістити теку/файл

=== Збереження змін (коміт)

 Команда                               | Опис
 ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 git commit -m "Повідомлення"          | Зберегти проіндексовані зміни (коміт)
 git commit -a -m "Повідомлення"       | Аналогічно git add . && git commit
 git commit --amend -m "Повідомлення"  | Доповнити (замінити) попередній коміт
 
 git log [--stat]                      | Звіт про історію комітів
 git log --pretty=oneline --abbrev-commit --graph
                                       | Історія комітів (один рядок на коміт)
                                       | з псевдографічним деревом історії
                                       | та скороченим гешем
 git log --pretty=format:"%h %an\t(%ae) %s" --date=short
                                       | Історія комітів (1 рядок, свій формат)


=== Скасування змін

 Команда                               | Опис
 ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 git checkout -- <файл>                | Відкинути зміни файлу, зроблені після
                                       | попереднього коміту (відновити з коміту)

=== Віддалені сховища

 Команда                               | Опис
 ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 git remote                            | Перелік підключених віддалених сховищ
 git remote add <сховище> <URL>        | Зареєструвати віддалене сховище
                                       | (тут <сховище> це локальна назва)
 git fetch <сховище>                   | Затягти увесь вміст віддаленого сховища
 git clone <URL> [<сховище>]           | Створення локальної копії віддаленого
                                       | сховища (локальна назва <сховище>, за
                                       | замовчуванням буде origin)
                                       | (remote add + fetch = clone?)
